#!/usr/bin/env python

import os
import subprocess

def here(*args): 
    return os.path.join(os.path.abspath(os.path.dirname(__file__)), *args)

def home(*args):
    home = os.getenv("HOME")
    return os.path.join(home, *args)

def main():
    for filename in ['bashrc', 'gitconfig', 'gitignore', 'gvimrc', 'vimrc', 'ackrc', 'bash_profile']:
        src = here(filename)
        dst = home('.' + filename)
        subprocess.call('rm %s' % dst, shell=True)
        subprocess.call("ln -s %s %s" % (src, dst), shell=True)
    for filename in ['local_bashrc']:
        src = here(filename)
        dst = home('.' + filename)
        subprocess.call("cp %s %s" % (src, dst), shell=True)
    subprocess.call("mkdir -p %s" % home('.vim', 'view'), shell=True)
    subprocess.call("mkdir -p %s" % home('.ssh'), shell=True)

if __name__ == '__main__':
    main()
